export enum responseMessage {
   'Book deleted!' = 1,
   'Book updated!' = 2,
   'Book created!' = 3,
   'Review deleted!' = 4,
   'Review created!' = 5,
   'Review updated!' = 22,
   'The necessary data is not provided!' = 6,
   'There is no book with such ID!' = 7,
   'The username is taken!' = 8,
   'User created!' = 9,
   'Book was borrowed!' = 10,
   'Book was returned!' = 11,
   'You\'re already borrowing this book!' = 12,
   'You can\'t return a book that you\'re not borrowing duh!' = 13,
   'There\'s no review with such ID!' = 14,
   'You can not edit this review!' = 15,
   'You must log in to perform this action!' = 16,
   'You need admin privileges to perform this action!' = 17,
   'Invalid username or password!' = 18,
   'You have been logged out!' = 19,
   'Display name has been updated!' = 20,
   'User has been deleted!' = 21,
   'User was banned!' = 23,
   'You liked this review!' = 24,
   'You disliked this review!' = 25,
}